replicaCount: 1
namespace: demo
externalSecret:
  create: true
  secretName: app-config #Your secret name in k8s
  keyNameInSecret: app-config.txt #Name of the key in k8s secret
  secretNameInAzurekv: my-key # Secret name in Azure keyvault
image:
  repository: ktcplatformregistry.azurecr.io/nodejs-app
  pullPolicy: IfNotPresent
  tag: "1.4"

deployment:
  annotations:
    reloader.stakater.com/auto: "true"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumeMounts:
  mountPath: /etc/secrets