replicaCount: 1
namespace: demo
externalSecret:
  create: true
  secretName: app-config #Your secret name in k8s
  keyNameInSecret: app-config.txt #Name of the key in k8s secret
  secretNameInAzurekv: test-key1 # Secret name in Azure keyvault
image:
  repository: ktcplatformregistry.azurecr.io/nodejs-app
  pullPolicy: IfNotPresent
  tag: "1.4"

deployment:
  annotations:
    reloader.stakater.com/auto: "true"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "external-nginx"
  annotations:
    cert-manager.io/issuer: "caissuer"
  hosts:
    - host: node.platform.kapsch-dev.net
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
      - node.platform.kapsch-dev.net
    secretName: root-secret

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumeMounts:
  mountPath: /etc/secrets
