{{- if .Values.externalSecret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name:  {{ include "nodejs-app.secretName" . }} # Name of the Kubernetes secret to create
    creationPolicy: Owner # Optional: how to handle the secret's lifecycle
  data:
  - secretKey: {{ .Values.externalSecret.keyNameInSecret }} # Key in the Kubernetes secret
    remoteRef:
      key: {{ .Values.externalSecret.secretNameInAzurekv }} # Name of the secret in Azure Key Vault
{{- end }}