{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: "caissuer"
  name: node
  namespace: {{ .Values.namespace }}
spec:
  tls:
  - hosts:
      - node.platform.kapsch-dev.net
    secretName: root-secret
  ingressClassName: external-nginx
  rules:
  - host: node.platform.kapsch-dev.net
    http:
      paths:
      - backend:
          service:
            name: {{ include "nodejs-app.fullname" . }}
            port:
              number: 3000
        path: /
        pathType: Prefix
{{- end }}